### ISSUE TITLE
Select options are not pressable

### ISSUE THREAD

**Issue by teimurjan** [roll-network/tryrolljs#398]
# Description

Because of the overlaying, `SelectV2`'s options are not pressable

![Screenshot 2023-07-27 at 14.34.56.png](https://images.zenhubusercontent.com/62f2604c15cd36270e5dc46c/514f17bb-e921-42c8-907b-b2cb92070fb5)

**Comment by marlon-wiprud** [comment]
@teimurjan is this closeable?
